use Training2023

SELECT * FROM TBL_CUSTOMER_DETAIL

CREATE TABLE TBL_CUSTOMER_DETAIL(
    CUSTOMER_ID int ,
    CUSTOMER_NAME varchar(255),
    CUSTOMER_AGE INT,
    CUSTOMER_ADDRESS varchar(255),
);

INSERT INTO TBL_CUSTOMER_DETAIL
VALUES(1,'KABILAN',20,'NAMAKKAL'),
(2,'SIVALINGAM',21,'KASHMIR'),
(3,'MANIKANDAN',22,'COVAI'),
(4,'MADHAVAN',23,'CHENNAI'),
(5,'SURENDHAR',24,'SALEM');